FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get install openjdk-8-jdk -y
RUN mkdir /opt/tomcat
WORKDIR /opt/tomcat/
ADD  https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.22/bin/apache-tomcat-10.0.22.tar.gz .
RUN tar xvfz apache-tomcat-10.0.22.tar.gz
COPY sample.war /opt/tomcat/apache-tomcat-10.0.22/webapps/
EXPOSE 8080
CMD  ["/opt/tomcat/apache-tomcat-10.0.22/bin/catalina.sh","run"]
